name: english-learning-platform
region: nyc
services:
  - name: web
    github:
      repo: YOUR_GITHUB_USERNAME/YOUR_REPO_NAME
      branch: master
      deploy_on_push: true
    build_command: pip install -r requirements.txt
    run_command: uvicorn app.main:app --host 0.0.0.0 --port 8080
    http_port: 8080
    instance_count: 1
    instance_size_slug: basic-xxs
    envs:
      - key: OPENROUTER_API_KEY
        scope: RUN_TIME
        type: SECRET
databases:
  # Note: SQLite won't persist on App Platform. Consider upgrading to PostgreSQL for production.
  # Uncomment below to add PostgreSQL:
  # - name: db
  #   engine: PG
  #   version: "14"

